# 向开发板发送固件更新数据，开发板会将数据写入 OTA Temp 区域
# 所有 chunk 发送完毕后，发送 OTA 命令进行应用

# Goal
uint32 offset      # Byte offset in the firmware image
uint8[] data       # Firmware data chunk
---
# Result
bool success
string msg
---
# Feedback
float32 progress   # 0.0 ~ 1.0 写入进度
