# Battery charging current limit
float32 charge_current_limit_a

# Battery charging voltage limit
float32 charge_voltage_limit_v

# Charging protection temperature
float32 charge_protection_temp

# Charging temperature limit
float32 charge_protection_temp_limit

# Servo power supply temperature limit
float32 servo_power_temp_limit

# Servo power supply current limit
float32 servo_power_current_limit

# 5V power supply temperature limit
float32 power_5v_temp_limit

